name: Deploy Github Pages

on:
  push:
    branches:
      - main
jobs:
  publish:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install node v16
        uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - name: install
        run: yarn install --frozen-lockfile
      - name: build
        run: yarn build-pages
      - name: test
        run: yarn test
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
